## Metodo GAUSS JORDAN

In [6]:
#Primer sistema.
import numpy as np
A = np.array([[4,-2,1],[-2,4,-2],[1,-2,4]])
b = np.array([[11],[-16],[17]])
Primer = np.linalg.solve(A,b)
Primer

array([[ 1.],
       [-2.],
       [ 3.]])

In [7]:
#Segundo sistema
import numpy as np
A = np.array([[1,1,1],[1,2,5],[1,4,25]])
b = np.array([[6],[12],[36]])
Segundo = np.linalg.solve(A,b)
Segundo

array([[3.],
       [2.],
       [1.]])

In [8]:
#Tercer sistema
import numpy as np
A = np.array([[1,2,1],[3,8,1],[0,4,1]])
b = np.array([[2],[12],[2]])
Tercer = np.linalg.solve(A,b)
Tercer

array([[ 2.],
       [ 1.],
       [-2.]])

## Metodo de la matriz inversa, $x = A^{-1}b$

In [9]:
#Primer sistema
import numpy as np
A = np.array([[4,-2,1],[-2,4,-2],[1,-2,4]])
b = np.array([[11],[-16],[17]])
#Comprobamos la matriz inversa
np.linalg.inv(A)

array([[0.33333333, 0.16666667, 0.        ],
       [0.16666667, 0.41666667, 0.16666667],
       [0.        , 0.16666667, 0.33333333]])

In [10]:
#Comprobamos la solucion.
x = np.linalg.inv(A)@b
x

array([[ 1.],
       [-2.],
       [ 3.]])

In [11]:
#Segundo sistema
import numpy as np
A = np.array([[1,1,1],[1,2,5],[1,4,25]])
b = np.array([[6],[12],[36]])
#Comprobamos la matriz inversa
np.linalg.inv(A)

array([[ 2.5       , -1.75      ,  0.25      ],
       [-1.66666667,  2.        , -0.33333333],
       [ 0.16666667, -0.25      ,  0.08333333]])

In [12]:
#Comprobamos la solucion.
x = np.linalg.inv(A)@b
x

array([[3.],
       [2.],
       [1.]])

In [13]:
#Tercer sistema
import numpy as np
A = np.array([[1,2,1],[3,8,1],[0,4,1]])
b = np.array([[2],[12],[2]])
#Comprobamos la matriz inversa
np.linalg.inv(A)

array([[ 0.4,  0.2, -0.6],
       [-0.3,  0.1,  0.2],
       [ 1.2, -0.4,  0.2]])

In [14]:
#Comprobamos la solucion.
x = np.linalg.inv(A)@b
x

array([[ 2.],
       [ 1.],
       [-2.]])

## Metodo de Cramer

In [15]:
#Primer sistema
#b = [11,-16,17]
import numpy as np
A = np.array([[4,-2,1],[-2,4,-2],[1,-2,4]])
X_1 = np.array([[11,-2,1],[-16,4,-2],[17,-2,4]])
Y_1 = np.array([[4,11,1],[-2,-16,-2],[1,17,4]])
Z_1 = np.array([[4,-2,11],[-2,4,-16],[1,-2,17]])
X = np.linalg.det(X_1)/np.linalg.det(A)
Y = np.linalg.det(Y_1)/np.linalg.det(A)
Z = np.linalg.det(Z_1)/np.linalg.det(A)
print(f'Los determinantes son Dg={np.linalg.det(A)} Dx={np.linalg.det(X_1)}, Dy={np.linalg.det(Y_1)}, Dz={np.linalg.det(Z_1)}')
print(f'Las soluciones son x={X}, y={Y}, z={Z}')

Los determinantes son Dg=36.0 Dx=36.0, Dy=-72.0, Dz=108.00000000000003
Las soluciones son x=1.0, y=-2.0, z=3.000000000000001


In [16]:
#Segundo sistema
#b = [6,12,36]
import numpy as np
A = np.array([[1,1,1],[1,2,5],[1,4,25]])
X_1 = np.array([[6,1,1],[12,2,5],[36,4,25]])
Y_1 = np.array([[1,6,1],[1,12,5],[1,36,25]])
Z_1 = np.array([[1,1,6],[1,2,12],[1,4,36]])
X = np.linalg.det(X_1)/np.linalg.det(A)
Y = np.linalg.det(Y_1)/np.linalg.det(A)
Z = np.linalg.det(Z_1)/np.linalg.det(A)
print(f'Los determinantes son Dg={np.linalg.det(A)} Dx={np.linalg.det(X_1)}, Dy={np.linalg.det(Y_1)}, Dz={np.linalg.det(Z_1)}')
print(f'Las soluciones son x={X}, y={Y}, z={Z}')

Los determinantes son Dg=12.0 Dx=36.0, Dy=24.000000000000025, Dz=12.0
Las soluciones son x=3.0, y=2.000000000000002, z=1.0


In [17]:
#Tercer sistema
#b = [2,12,2]
import numpy as np
A = np.array([[1,2,1],[3,8,1],[0,4,1]])
X_1 = np.array([[2,2,1],[12,8,1],[2,4,1]])
Y_1 = np.array([[1,2,1],[3,12,1],[0,2,1]])
Z_1 = np.array([[1,2,2],[3,8,12],[0,4,2]])
X = np.linalg.det(X_1)/np.linalg.det(A)
Y = np.linalg.det(Y_1)/np.linalg.det(A)
Z = np.linalg.det(Z_1)/np.linalg.det(A)
print(f'Los determinantes son Dg={np.linalg.det(A)} Dx={np.linalg.det(X_1)}, Dy={np.linalg.det(Y_1)}, Dz={np.linalg.det(Z_1)}')
print(f'Las soluciones son x={X}, y={Y}, z={Z}')

Los determinantes son Dg=9.999999999999998 Dx=19.999999999999996, Dy=10.000000000000002, Dz=-20.000000000000007
Las soluciones son x=2.0, y=1.0000000000000004, z=-2.000000000000001


# Metodo de LU por algoritmo de Dolittle

In [18]:
#Segundo sistema
import numpy as np
A = np.array([[1,1,1],[1,2,5],[1,4,25]])
L= np.zeros((3,3))
U= np.zeros((3,3))
#Los elementos d ela diagonal principal son 1
L[0][0] = 1
L[1][1] = 1
L[2][2] = 1
U[0,:] = A[0,:] #primera fila de A es la misma de U
L[1][0] = A[1][0]/U[0][0]
U[1][1] = A[1][1] - L[1][0]*U[0][1] #Se estan siguiendo las formulitas
U[1][2] = A[1][2]-L[1][0]*U[0][2]
L[2][0] = A[2][0]/U[0][0]
L[2][1] = (A[2][1]-L[2][0]*U[0][1])/U[1][1]
U[2][2] = A[2][2]-L[2][0]*U[0][2]-L[2][1]*U[1][2]
b = np.array([[6],[12],[36]])
Z = np.linalg.solve(L,b)
X = np.linalg.solve(U,Z)
X

array([[3.],
       [2.],
       [1.]])

In [19]:
A = L@U
A

array([[ 1.,  1.,  1.],
       [ 1.,  2.,  5.],
       [ 1.,  4., 25.]])

In [20]:
#Tercer sitema
import numpy as np
A = np.array([[1,2,1],[3,8,1],[0,4,1]])
L= np.zeros((3,3))
U= np.zeros((3,3))
#Los elementos d ela diagonal principal son 1
L[0][0] = 1
L[1][1] = 1
L[2][2] = 1
U[0,:] = A[0,:] #primera fila de A es la misma de U
L[1][0] = A[1][0]/U[0][0]
U[1][1] = A[1][1] - L[1][0]*U[0][1] #Se estan siguiendo las formulitas
U[1][2] = A[1][2]-L[1][0]*U[0][2]
L[2][0] = A[2][0]/U[0][0]
L[2][1] = (A[2][1]-L[2][0]*U[0][1])/U[1][1]
U[2][2] = A[2][2]-L[2][0]*U[0][2]-L[2][1]*U[1][2]
b = np.array([[2],[12],[2]])
Z = np.linalg.solve(L,b)
X = np.linalg.solve(U,Z)
X

array([[ 2.],
       [ 1.],
       [-2.]])

In [21]:
A = L@U
A

array([[1., 2., 1.],
       [3., 8., 1.],
       [0., 4., 1.]])

#Comprobacion Cholesky
Solo del sistema (2), en el sistema (3) no hay descomposicion Cholesky.

In [22]:
#Segundo sistema
import numpy as np
A = np.array([[1,1,1],[1,2,5],[1,4,25]])
L= np.zeros((3,3))
L[0][0] = np.sqrt(A[0][0])
L[1][0] = A[1][0]/L[0][0]
L[2][0] = A[2][0]/L[0][0]
L[1][1] = np.sqrt(A[1][1]-L[1][0]**2)
L[2][1] = (A[2][1]-L[1][0]*L[2][0])/L[1][1]
L[2][2] = np.sqrt(A[2][2]-L[2][0]**2-L[2][1]**2)
Lt = np.transpose(L)
A0 = L@Lt
A0

array([[ 1.,  1.,  1.],
       [ 1.,  2.,  4.],
       [ 1.,  4., 25.]])

# Metodo Jacobi.

In [38]:
import numpy as np
A = np.array([[1,-0.1,-0.2],[0.1,7,-0.3],[0.3,-0.2,-10]])
b = np.array([[7.85],[19.3],[71.4]])
error_rel = lambda vn, vv: (np.abs(vn - vv)/np.abs(vn))*100

x1_viejo = 0;
x2_viejo = 0;
x3_viejo = 0;
num_iteraciones = 5;

for i in range(num_iteraciones):
  x1_nuevo = round((b[0][0]-A[0][1]*x2_viejo-A[0][2]*x3_viejo)/A[0][0],4)
  x2_nuevo = round((b[1][0]-A[1][0]*x1_viejo-A[1][2]*x3_viejo)/A[1][1],4)
  x3_nuevo = round((b[2][0]-A[2][0]*x1_viejo-A[2][1]*x2_viejo)/A[2][2],4)
  print(f'i={i+1}\n')
  print(f'x1= {x1_nuevo} ; x2= {x2_nuevo} ; x3= {x3_nuevo}\n')
  error_x1 = round(error_rel(x1_nuevo,x1_viejo),4)
  error_x2 = round(error_rel(x2_nuevo,x2_viejo),4)
  error_x3 = round(error_rel(x3_nuevo,x3_viejo),4)
  x1_viejo = x1_nuevo
  x2_viejo = x2_nuevo
  x3_viejo = x3_nuevo
  print(f'Er(x1)= {error_x1} ; Er(x2)= {error_x2} ; Er(x3)= {error_x3}\n')
  print('\n')

i=1

x1= 7.85 ; x2= 2.7571 ; x3= -7.14

Er(x1)= 100.0 ; Er(x2)= 100.0 ; Er(x3)= 100.0



i=2

x1= 6.6977 ; x2= 2.339 ; x3= -6.9596

Er(x1)= 17.2044 ; Er(x2)= 17.8752 ; Er(x3)= 2.5921



i=3

x1= 6.692 ; x2= 2.3632 ; x3= -6.9858

Er(x1)= 0.0852 ; Er(x2)= 1.024 ; Er(x3)= 0.375



i=4

x1= 6.6892 ; x2= 2.3622 ; x3= -6.9865

Er(x1)= 0.0419 ; Er(x2)= 0.0423 ; Er(x3)= 0.01



i=5

x1= 6.6889 ; x2= 2.3622 ; x3= -6.9866

Er(x1)= 0.0045 ; Er(x2)= 0.0 ; Er(x3)= 0.0014





# Metodo Gauss-Seidel

In [37]:
import numpy as np
A = np.array([[1,-0.1,-0.2],[0.1,7,-0.3],[0.3,-0.2,-10]])
b = np.array([[7.85],[19.3],[71.4]])
error_rel = lambda vn, vv: (np.abs(vn - vv)/np.abs(vn))*100

x1_viejo = 0;
x2_viejo = 0;
x3_viejo = 0;
num_iteraciones = 5;

for i in range(num_iteraciones):
  x1_nuevo = round((b[0][0]-A[0][1]*x2_viejo-A[0][2]*x3_viejo)/A[0][0],4)
  x2_nuevo = round((b[1][0]-A[1][0]*x1_nuevo-A[1][2]*x3_viejo)/A[1][1],4)
  x3_nuevo = round((b[2][0]-A[2][0]*x1_nuevo-A[2][1]*x2_nuevo)/A[2][2],4)
  print(f'i={i+1}')
  print(f'x1= {x1_nuevo} ; x2= {x2_nuevo} ; x3= {x3_nuevo}\n')
  error_x1 = round(error_rel(x1_nuevo,x1_viejo),4)
  error_x2 = round(error_rel(x2_nuevo,x2_viejo),4)
  error_x3 = round(error_rel(x3_nuevo,x3_viejo),4)
  x1_viejo = x1_nuevo
  x2_viejo = x2_nuevo
  x3_viejo = x3_nuevo
  print(f'Er(x1)= {error_x1} ; Er(x2)= {error_x2} ; Er(x3)= {error_x3}\n')
  print('\n')

i=1
x1= 7.85 ; x2= 2.645 ; x3= -6.9574

Er(x1)= 100.0 ; Er(x2)= 100.0 ; Er(x3)= 100.0



i=2
x1= 6.723 ; x2= 2.3629 ; x3= -6.9856

Er(x1)= 16.7633 ; Er(x2)= 11.9387 ; Er(x3)= 0.4037



i=3
x1= 6.6892 ; x2= 2.3622 ; x3= -6.9866

Er(x1)= 0.5053 ; Er(x2)= 0.0296 ; Er(x3)= 0.0143



i=4
x1= 6.6889 ; x2= 2.3622 ; x3= -6.9866

Er(x1)= 0.0045 ; Er(x2)= 0.0 ; Er(x3)= 0.0



i=5
x1= 6.6889 ; x2= 2.3622 ; x3= -6.9866

Er(x1)= 0.0 ; Er(x2)= 0.0 ; Er(x3)= 0.0



